# Generated by Django 3.2.9 on 2022-01-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('newsletters', '0002_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateNewsletter',
            new_name='Newsletters',
        ),
        migrations.AlterModelOptions(
            name='newsletters',
            options={'verbose_name_plural': 'Newsletters'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
