# Generated by Django 3.2.9 on 2022-01-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20220109_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
