# Generated by Django 3.2.9 on 2021-12-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, choices=[('6', 'Size 6'), ('8', 'Size 8'), ('10', 'Size 10'), ('12', 'Size 12'), ('14', 'Size 14'), ('16', 'Size 16'), ('18', 'Size 18'), ('20', 'Size 20')], max_length=2, null=True),
        ),
    ]
