# Generated by Django 3.2.9 on 2021-12-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profiles',
            new_name='user_profile',
        ),
    ]
